//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git_system.MultiResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Multi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Multi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Git_system.MultiResources.Multi", typeof(Multi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TH.
        /// </summary>
        public static string @__LanguageType {
            get {
                return ResourceManager.GetString("__LanguageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กลับสู่หน้าหลัก.
        /// </summary>
        public static string _Button_BackToHome {
            get {
                return ResourceManager.GetString("_Button_BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิก.
        /// </summary>
        public static string _Button_Cancel {
            get {
                return ResourceManager.GetString("_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชำระเงิน.
        /// </summary>
        public static string _Button_Checkout {
            get {
                return ResourceManager.GetString("_Button_Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยัน.
        /// </summary>
        public static string _Button_confirm {
            get {
                return ResourceManager.GetString("_Button_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการชำระเงิน.
        /// </summary>
        public static string _Button_confirmPayment {
            get {
                return ResourceManager.GetString("_Button_confirmPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลืมรหัสผ่าน.
        /// </summary>
        public static string _Button_ForgetPassword {
            get {
                return ResourceManager.GetString("_Button_ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เข้าสู่ระบบ.
        /// </summary>
        public static string _Button_Login {
            get {
                return ResourceManager.GetString("_Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขั้นตอนต่อไป.
        /// </summary>
        public static string _Button_Next {
            get {
                return ResourceManager.GetString("_Button_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ย้อนกลับ.
        /// </summary>
        public static string _Button_Prev {
            get {
                return ResourceManager.GetString("_Button_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลงทะเบียน.
        /// </summary>
        public static string _Button_Register {
            get {
                return ResourceManager.GetString("_Button_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่งข้อมูล.
        /// </summary>
        public static string _Button_SendResetPasswordLink {
            get {
                return ResourceManager.GetString("_Button_SendResetPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประวัติการสั่งซื้อ.
        /// </summary>
        public static string _HomePaymentHistory {
            get {
                return ResourceManager.GetString("_HomePaymentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะการสั่งซื้อ.
        /// </summary>
        public static string _HomePaymentStatus {
            get {
                return ResourceManager.GetString("_HomePaymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ต่อไป.
        /// </summary>
        public static string _HomeString_Next {
            get {
                return ResourceManager.GetString("_HomeString_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ย้อนกลับ.
        /// </summary>
        public static string _HomeString_Prev {
            get {
                return ResourceManager.GetString("_HomeString_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายการสั่งซื้อ.
        /// </summary>
        public static string _HomeString1 {
            get {
                return ResourceManager.GetString("_HomeString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มีรายการสั่งซื้อที่ค้างชำระในขณะนี้.
        /// </summary>
        public static string _HomeString10 {
            get {
                return ResourceManager.GetString("_HomeString10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มีรายการสั่งซื้อในขณะนี้.
        /// </summary>
        public static string _HomeString11 {
            get {
                return ResourceManager.GetString("_HomeString11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สมัครสมาชิกเพื่อรับส่วนลดค่าหลักสูตรอบรม.
        /// </summary>
        public static string _HomeString2 {
            get {
                return ResourceManager.GetString("_HomeString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สมาชิกประเภทบุคคลธรรมดา.
        /// </summary>
        public static string _HomeString3 {
            get {
                return ResourceManager.GetString("_HomeString3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สมาชิกหมดอายุแล้ว.
        /// </summary>
        public static string _HomeString4 {
            get {
                return ResourceManager.GetString("_HomeString4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมดอายุ.
        /// </summary>
        public static string _HomeString5 {
            get {
                return ResourceManager.GetString("_HomeString5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สมาชิกประเภทนิติบุคคล.
        /// </summary>
        public static string _HomeString6 {
            get {
                return ResourceManager.GetString("_HomeString6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายการสั่งซื้อที่ค้างชำระ.
        /// </summary>
        public static string _HomeString7 {
            get {
                return ResourceManager.GetString("_HomeString7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่ทำการสั่งซื้อ.
        /// </summary>
        public static string _HomeString8 {
            get {
                return ResourceManager.GetString("_HomeString8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคาที่ต้องชำระ.
        /// </summary>
        public static string _HomeString9 {
            get {
                return ResourceManager.GetString("_HomeString9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login (E-SERVICE).
        /// </summary>
        public static string _IndexString_Head_Title {
            get {
                return ResourceManager.GetString("_IndexString_Head_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมล.
        /// </summary>
        public static string _IndexString1 {
            get {
                return ResourceManager.GetString("_IndexString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผ่าน.
        /// </summary>
        public static string _IndexString2 {
            get {
                return ResourceManager.GetString("_IndexString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คลิกที่นี่.
        /// </summary>
        public static string _MembershipRegisterString_legal {
            get {
                return ResourceManager.GetString("_MembershipRegisterString_legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หัวข้อ.
        /// </summary>
        public static string _MembershipRegisterString1 {
            get {
                return ResourceManager.GetString("_MembershipRegisterString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณายอมรับข้อกำหนดและเงื่อนไขเพื่อดำเนินการชำระเงินต่อไป.
        /// </summary>
        public static string _MembershipRegisterString10 {
            get {
                return ResourceManager.GetString("_MembershipRegisterString10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงื่อนไขและหลักเกณฑ์การคืนเงินค่าบริการให้กับผู้สมัครเข้ารับการฝึกอบรม กรุณา.
        /// </summary>
        public static string _MembershipRegisterString11 {
            get {
                return ResourceManager.GetString("_MembershipRegisterString11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภท.
        /// </summary>
        public static string _MembershipRegisterString2 {
            get {
                return ResourceManager.GetString("_MembershipRegisterString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคา.
        /// </summary>
        public static string _MembershipRegisterString3 {
            get {
                return ResourceManager.GetString("_MembershipRegisterString3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วิธีการชำระเงิน.
        /// </summary>
        public static string _MembershipRegisterString4 {
            get {
                return ResourceManager.GetString("_MembershipRegisterString4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โอนเงิน / Transfer.
        /// </summary>
        public static string _MembershipRegisterString5 {
            get {
                return ResourceManager.GetString("_MembershipRegisterString5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card.
        /// </summary>
        public static string _MembershipRegisterString6 {
            get {
                return ResourceManager.GetString("_MembershipRegisterString6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคาสินค้า.
        /// </summary>
        public static string _MembershipRegisterString7 {
            get {
                return ResourceManager.GetString("_MembershipRegisterString7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่วนลด.
        /// </summary>
        public static string _MembershipRegisterString8 {
            get {
                return ResourceManager.GetString("_MembershipRegisterString8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคาทั้งหมด.
        /// </summary>
        public static string _MembershipRegisterString9 {
            get {
                return ResourceManager.GetString("_MembershipRegisterString9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงื่อนไขและหลักเกณฑ์การคืนเงินค่าบริการให้กับผู้สมัครเข้ารับการบริการ กรุณา.
        /// </summary>
        public static string _MembershipRegisterStringLegal {
            get {
                return ResourceManager.GetString("_MembershipRegisterStringLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคาหลักสูตร.
        /// </summary>
        public static string _Payment_string1 {
            get {
                return ResourceManager.GetString("_Payment_string1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สมาชิก.
        /// </summary>
        public static string _RegisterMembership {
            get {
                return ResourceManager.GetString("_RegisterMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แบบฟอร์มสำหรับสมัครสมาชิก.
        /// </summary>
        public static string _RegisterMembershipString1 {
            get {
                return ResourceManager.GetString("_RegisterMembershipString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การลงทะเบียนสำเร็จ.
        /// </summary>
        public static string _RegisterStep3String1 {
            get {
                return ResourceManager.GetString("_RegisterStep3String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาตรวจสอบอีเมลของท่านเพื่อยืนยันการลงทะเบียน.
        /// </summary>
        public static string _RegisterStep3String2 {
            get {
                return ResourceManager.GetString("_RegisterStep3String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลืมรหัสผ่าน ?.
        /// </summary>
        public static string _SendResetPasswordString1 {
            get {
                return ResourceManager.GetString("_SendResetPasswordString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ป้อนอีเมลแอดเดรสของคุณด้านล่าง และเราจะส่งลิงค์ให้คุณรีเซ็ตรหัสผ่านของคุณ.
        /// </summary>
        public static string _SendResetPasswordString2 {
            get {
                return ResourceManager.GetString("_SendResetPasswordString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการชำระเงิน.
        /// </summary>
        public static string _TitlePage_Head_ConfirmPayment {
            get {
                return ResourceManager.GetString("_TitlePage_Head_ConfirmPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แบบฟอร์มลงทะเบียน.
        /// </summary>
        public static string _TitlePage_Head_RegisterStep1 {
            get {
                return ResourceManager.GetString("_TitlePage_Head_RegisterStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แบบฟอร์มลงทะเบียน.
        /// </summary>
        public static string _TitlePage_Head_RegisterStep2 {
            get {
                return ResourceManager.GetString("_TitlePage_Head_RegisterStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แบบฟอร์มลงทะเบียน.
        /// </summary>
        public static string _TitlePage_Head_RegisterStep3 {
            get {
                return ResourceManager.GetString("_TitlePage_Head_RegisterStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการชำระเงิน.
        /// </summary>
        public static string _TitleWeb_ConfirmPayment {
            get {
                return ResourceManager.GetString("_TitleWeb_ConfirmPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไขโปรไฟล์.
        /// </summary>
        public static string _TitleWeb_Edit_Profile {
            get {
                return ResourceManager.GetString("_TitleWeb_Edit_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หน้าหลัก.
        /// </summary>
        public static string _TitleWeb_Home {
            get {
                return ResourceManager.GetString("_TitleWeb_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เข้าสู่ระบบ.
        /// </summary>
        public static string _TitleWeb_Index {
            get {
                return ResourceManager.GetString("_TitleWeb_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สมาชิก.
        /// </summary>
        public static string _TitleWeb_MembershipRegister {
            get {
                return ResourceManager.GetString("_TitleWeb_MembershipRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การชำระเงิน.
        /// </summary>
        public static string _TitleWeb_Payment {
            get {
                return ResourceManager.GetString("_TitleWeb_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หลักสูตร.
        /// </summary>
        public static string _TitleWeb_Product {
            get {
                return ResourceManager.GetString("_TitleWeb_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string _TitleWeb_RegisterStep {
            get {
                return ResourceManager.GetString("_TitleWeb_RegisterStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รีเซ็ตรหัสผ่าน.
        /// </summary>
        public static string _TitleWeb_SendResetPassword {
            get {
                return ResourceManager.GetString("_TitleWeb_SendResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเนาบัตรประชาชน.
        /// </summary>
        public static string A_photocopy_of_ID_card {
            get {
                return ResourceManager.GetString("A_photocopy_of_ID_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบทะเบียนภาษีมูลค่าเพิ่ม (ภพ.20).
        /// </summary>
        public static string A_photocopy_of_VAT_registration_VAT20 {
            get {
                return ResourceManager.GetString("A_photocopy_of_VAT_registration_VAT20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบบได้ทำการบันทึกรายการยืนยันการสั่งซื้อเรียบร้อยแล้ว.
        /// </summary>
        public static string ActionConfirmPaymentShowMessageBody {
            get {
                return ResourceManager.GetString("ActionConfirmPaymentShowMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขอบคุณที่ใช้บริการ.
        /// </summary>
        public static string ActionConfirmPaymentShowMessageHead {
            get {
                return ResourceManager.GetString("ActionConfirmPaymentShowMessageHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการชำระเงิน.
        /// </summary>
        public static string ActionConfirmPaymentShowMessageTitle {
            get {
                return ResourceManager.GetString("ActionConfirmPaymentShowMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบบจะส่งรายละเอียดการชำระเงินไปทางอีเมลที่ได้ลงทะเบียนไว้กับระบบ.
        /// </summary>
        public static string ActionMembershipRegisterShowMessageBody {
            get {
                return ResourceManager.GetString("ActionMembershipRegisterShowMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขอบคุณที่ใช้บริการ.
        /// </summary>
        public static string ActionMembershipRegisterShowMessageHead {
            get {
                return ResourceManager.GetString("ActionMembershipRegisterShowMessageHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สมัครสมาชิก.
        /// </summary>
        public static string ActionMembershipRegisterShowMessageTitle {
            get {
                return ResourceManager.GetString("ActionMembershipRegisterShowMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบบจะส่งรายละเอียดการชำระเงินไปทางอีเมลที่ได้ลงทะเบียนไว้กับระบบ.
        /// </summary>
        public static string ActionPaymentShowMessageBody {
            get {
                return ResourceManager.GetString("ActionPaymentShowMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขอบคุณที่ใช้บริการ.
        /// </summary>
        public static string ActionPaymentShowMessageHead {
            get {
                return ResourceManager.GetString("ActionPaymentShowMessageHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลงทะเบียนออนไลน์.
        /// </summary>
        public static string ActionPaymentShowMessageTitle {
            get {
                return ResourceManager.GetString("ActionPaymentShowMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลจากสมาชิกสถาบัน สวอ..
        /// </summary>
        public static string ActionRegisterStep2String1 {
            get {
                return ResourceManager.GetString("ActionRegisterStep2String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สมัครสมาชิกใหม่.
        /// </summary>
        public static string ActionRegisterStep2String2 {
            get {
                return ResourceManager.GetString("ActionRegisterStep2String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทำการเปลี่ยนรหัสผ่านเสร็จสำบูรณ์.
        /// </summary>
        public static string ActionResetPasswordShowMessageBody {
            get {
                return ResourceManager.GetString("ActionResetPasswordShowMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รีเซ็ตรหัสผ่าน.
        /// </summary>
        public static string ActionResetPasswordShowMessageHead {
            get {
                return ResourceManager.GetString("ActionResetPasswordShowMessageHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รีเซ็ตรหัสผ่าน.
        /// </summary>
        public static string ActionResetPasswordShowMessageTitle {
            get {
                return ResourceManager.GetString("ActionResetPasswordShowMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาตรวจสอบอีเมลของท่านเพื่อตั้งรหัสผ่านใหม่ภายในระยะเวลา 1 ชั่วโมง.
        /// </summary>
        public static string ActionSendResetPasswordShowMessageBody {
            get {
                return ResourceManager.GetString("ActionSendResetPasswordShowMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลของท่านถูกต้อง.
        /// </summary>
        public static string ActionSendResetPasswordShowMessageHead {
            get {
                return ResourceManager.GetString("ActionSendResetPasswordShowMessageHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รีเซ็ตรหัสผ่าน.
        /// </summary>
        public static string ActionSendResetPasswordShowMessageTitle {
            get {
                return ResourceManager.GetString("ActionSendResetPasswordShowMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หยิบใส่ตะกร้า.
        /// </summary>
        public static string Add_to_cart {
            get {
                return ResourceManager.GetString("Add_to_cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่ออกใบเสร็จรับเงิน.
        /// </summary>
        public static string Address_for_receipt {
            get {
                return ResourceManager.GetString("Address_for_receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่จากข้อมูลการสมัคร.
        /// </summary>
        public static string Address_is_based_on_registration_data {
            get {
                return ResourceManager.GetString("Address_is_based_on_registration_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่จากที่อยู่การจัดส่ง.
        /// </summary>
        public static string Address_is_based_on_The_address_of_delivery {
            get {
                return ResourceManager.GetString("Address_is_based_on_The_address_of_delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ย้อนกลับ.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สิทธิประโยชน์.
        /// </summary>
        public static string Benefit {
            get {
                return ResourceManager.GetString("Benefit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ภาพตัวอักษร.
        /// </summary>
        public static string CaptchaImage {
            get {
                return ResourceManager.GetString("CaptchaImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมวดหมู่.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เปลี่ยนรหัสผ่าน.
        /// </summary>
        public static string Change_password {
            get {
                return ResourceManager.GetString("Change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมลหรือรหัสผ่านไม่ถูกต้อง.
        /// </summary>
        public static string CheckEmailOrPassword {
            get {
                return ResourceManager.GetString("CheckEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมลยังไม่ได้รับการยืนยัน {0}.
        /// </summary>
        public static string CheckMembershipActive {
            get {
                return ResourceManager.GetString("CheckMembershipActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกชนิดข้อมูล.
        /// </summary>
        public static string Choose_category {
            get {
                return ResourceManager.GetString("Choose_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกไฟล์.
        /// </summary>
        public static string choose_file {
            get {
                return ResourceManager.GetString("choose_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เปลี่ยนรหัสผ่านเสร็จสมบูรณ์.
        /// </summary>
        public static string Complete_change_password {
            get {
                return ResourceManager.GetString("Complete_change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยัน.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการสั่งซื้อ.
        /// </summary>
        public static string Confirm_ordering {
            get {
                return ResourceManager.GetString("Confirm_ordering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชำระเข้าธนาคาร.
        /// </summary>
        public static string ConfirmPayment_ConfirmPaymentBank {
            get {
                return ResourceManager.GetString("ConfirmPayment_ConfirmPaymentBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วัน-เวลาที่ชำระ.
        /// </summary>
        public static string ConfirmPayment_Date {
            get {
                return ResourceManager.GetString("ConfirmPayment_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่ชำระ.
        /// </summary>
        public static string ConfirmPayment_DateDate {
            get {
                return ResourceManager.GetString("ConfirmPayment_DateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลาที่ชำระ.
        /// </summary>
        public static string ConfirmPayment_DateTime {
            get {
                return ResourceManager.GetString("ConfirmPayment_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แนบไฟล์.
        /// </summary>
        public static string ConfirmPayment_file {
            get {
                return ResourceManager.GetString("ConfirmPayment_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ-นามสกุล.
        /// </summary>
        public static string ConfirmPayment_Fullname {
            get {
                return ResourceManager.GetString("ConfirmPayment_Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเหตุ.
        /// </summary>
        public static string ConfirmPayment_Other {
            get {
                return ResourceManager.GetString("ConfirmPayment_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขที่การสั่งซื้อ.
        /// </summary>
        public static string ConfirmPayment_PayId {
            get {
                return ResourceManager.GetString("ConfirmPayment_PayId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขโทรศัพท์.
        /// </summary>
        public static string ConfirmPayment_Tel {
            get {
                return ResourceManager.GetString("ConfirmPayment_Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนเงิน.
        /// </summary>
        public static string ConfirmPayment_Total {
            get {
                return ResourceManager.GetString("ConfirmPayment_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดำเนินการต่อ.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเทศ.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การอบรม.
        /// </summary>
        public static string Course_Title {
            get {
                return ResourceManager.GetString("Course_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เอกสารรับรอง.
        /// </summary>
        public static string credentials {
            get {
                return ResourceManager.GetString("credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วัน-เวลา จัดส่ง.
        /// </summary>
        public static string Datetime_send {
            get {
                return ResourceManager.GetString("Datetime_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะการจัดส่ง.
        /// </summary>
        public static string Deliver_status {
            get {
                return ResourceManager.GetString("Deliver_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รูปเเบบการส่งสินค้า.
        /// </summary>
        public static string Deliver_type {
            get {
                return ResourceManager.GetString("Deliver_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่จัดส่งเเละการชำระเงิน.
        /// </summary>
        public static string Delivery_address_and_payment {
            get {
                return ResourceManager.GetString("Delivery_address_and_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่าจัดส่ง.
        /// </summary>
        public static string Delivery_cost {
            get {
                return ResourceManager.GetString("Delivery_cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่สำหรับจัดส่ง.
        /// </summary>
        public static string Delivery_payment {
            get {
                return ResourceManager.GetString("Delivery_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตัวอย่างไฟล์.
        /// </summary>
        public static string Demo_file {
            get {
                return ResourceManager.GetString("Demo_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายละเอียด.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดาวน์โหลดไฟล์.
        /// </summary>
        public static string Download_file {
            get {
                return ResourceManager.GetString("Download_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประสบการณ์ด้านอัญมณี.
        /// </summary>
        public static string DoyouhavestudyorworkexperienceinGemandJewelryField {
            get {
                return ResourceManager.GetString("DoyouhavestudyorworkexperienceinGemandJewelryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วัน.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไข.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมล.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมลถูกใช้แล้ว.
        /// </summary>
        public static string Email_Is_Using {
            get {
                return ResourceManager.GetString("Email_Is_Using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันหมดอายุสมาชิก CRM.
        /// </summary>
        public static string ExpiryDayCRM {
            get {
                return ResourceManager.GetString("ExpiryDayCRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ต่อ.
        /// </summary>
        public static string Ext {
            get {
                return ResourceManager.GetString("Ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกินข้อผิดพลาดในการชำระเงิน.
        /// </summary>
        public static string Failure_in_payment {
            get {
                return ResourceManager.GetString("Failure_in_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรอกข้อมูล.
        /// </summary>
        public static string Fill_in_the_form {
            get {
                return ResourceManager.GetString("Fill_in_the_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ฟรี! ไม่มีค่าใช้จ่าย.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ - นามสกุล.
        /// </summary>
        public static string Fullname {
            get {
                return ResourceManager.GetString("Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถาบันวิจัยและพัฒนาอัญมณีและเครื่องประดับแห่งชาติ (องค์การมหาชน).
        /// </summary>
        public static string GemInstituteName {
            get {
                return ResourceManager.GetString("GemInstituteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มี.
        /// </summary>
        public static string has {
            get {
                return ResourceManager.GetString("has", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วุฒิการศึกษาสูงสุด.
        /// </summary>
        public static string HighestLevelofEducation {
            get {
                return ResourceManager.GetString("HighestLevelofEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประวัติการสั่งซื้อ.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกบัตรประชาชน.
        /// </summary>
        public static string Identification_no_field_is_required {
            get {
                return ResourceManager.GetString("Identification_no_field_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสบัตรประชาชนต้องเป็นตัวเลขเท่านั้น.
        /// </summary>
        public static string Identification_no_must_be_numeric {
            get {
                return ResourceManager.GetString("Identification_no_must_be_numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขที่บัตรประชาชน.
        /// </summary>
        public static string IdentificationCardNo {
            get {
                return ResourceManager.GetString("IdentificationCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลำดับ.
        /// </summary>
        public static string IdNumber {
            get {
                return ResourceManager.GetString("IdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อความภาพตัวอักษรไม่ถูกต้อง.
        /// </summary>
        public static string Image_code_is_not_valid {
            get {
                return ResourceManager.GetString("Image_code_is_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลสมาชิก.
        /// </summary>
        public static string Information_of_membership {
            get {
                return ResourceManager.GetString("Information_of_membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วิธีใช้.
        /// </summary>
        public static string LayoutFrontend_String0 {
            get {
                return ResourceManager.GetString("LayoutFrontend_String0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หลักสูตร.
        /// </summary>
        public static string LayoutFrontend_String1 {
            get {
                return ResourceManager.GetString("LayoutFrontend_String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2013 The Gem and Jewelry Institute of Thailand (Public Organization). All rights reserved..
        /// </summary>
        public static string LayoutFrontend_String10 {
            get {
                return ResourceManager.GetString("LayoutFrontend_String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 140, 140/1-3, 140/5 อาคารไอทีเอฟ ทาวเวอร์ ชั้น 1 - 4 และชั้น 6 ถนนสีลม แขวงสุริยวงศ์ เขตบางรัก กรุงเทพฯ 10500.
        /// </summary>
        public static string LayoutFrontend_String11 {
            get {
                return ResourceManager.GetString("LayoutFrontend_String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โทรศัพท์ 0 2634 4999  โทรสาร 0 2634 4970  อีเมล jewelry@git.or.th.
        /// </summary>
        public static string LayoutFrontend_String12 {
            get {
                return ResourceManager.GetString("LayoutFrontend_String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สมาชิก.
        /// </summary>
        public static string LayoutFrontend_String13 {
            get {
                return ResourceManager.GetString("LayoutFrontend_String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สินค้า.
        /// </summary>
        public static string LayoutFrontend_String2 {
            get {
                return ResourceManager.GetString("LayoutFrontend_String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลส่วนตัว.
        /// </summary>
        public static string LayoutFrontend_String3 {
            get {
                return ResourceManager.GetString("LayoutFrontend_String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ออกจากระบบ.
        /// </summary>
        public static string LayoutFrontend_String4 {
            get {
                return ResourceManager.GetString("LayoutFrontend_String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลงทะเบียน.
        /// </summary>
        public static string LayoutFrontend_String5 {
            get {
                return ResourceManager.GetString("LayoutFrontend_String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เข้าสู่ระบบ.
        /// </summary>
        public static string LayoutFrontend_String6 {
            get {
                return ResourceManager.GetString("LayoutFrontend_String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สมาชิกสัมพันธ์.
        /// </summary>
        public static string LayoutFrontend_String7 {
            get {
                return ResourceManager.GetString("LayoutFrontend_String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นโยบายการคุ้มครองข้อมูลส่วนบุคคล.
        /// </summary>
        public static string LayoutFrontend_String8 {
            get {
                return ResourceManager.GetString("LayoutFrontend_String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แผนผังเว็บไซต์.
        /// </summary>
        public static string LayoutFrontend_String9 {
            get {
                return ResourceManager.GetString("LayoutFrontend_String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อกำหนด/เงื่อนไข.
        /// </summary>
        public static string Legal {
            get {
                return ResourceManager.GetString("Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานที่.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระยะยาว.
        /// </summary>
        public static string longTerm {
            get {
                return ResourceManager.GetString("longTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่.
        /// </summary>
        public static string Membership_Address {
            get {
                return ResourceManager.GetString("Membership_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อำเภอ/เขต.
        /// </summary>
        public static string Membership_Amphur {
            get {
                return ResourceManager.GetString("Membership_Amphur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำตอบ.
        /// </summary>
        public static string Membership_Answer {
            get {
                return ResourceManager.GetString("Membership_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันเกิด.
        /// </summary>
        public static string Membership_BirthDay {
            get {
                return ResourceManager.GetString("Membership_BirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เมือง.
        /// </summary>
        public static string Membership_City {
            get {
                return ResourceManager.GetString("Membership_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานที่ทำงาน (กรอกเฉพาะชื่อ).
        /// </summary>
        public static string Membership_Company {
            get {
                return ResourceManager.GetString("Membership_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเทศ.
        /// </summary>
        public static string Membership_Country {
            get {
                return ResourceManager.GetString("Membership_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตำบล/แขวง.
        /// </summary>
        public static string Membership_District {
            get {
                return ResourceManager.GetString("Membership_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมล.
        /// </summary>
        public static string Membership_Email {
            get {
                return ResourceManager.GetString("Membership_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันอีเมล.
        /// </summary>
        public static string Membership_Email_Re {
            get {
                return ResourceManager.GetString("Membership_Email_Re", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โทรสาร.
        /// </summary>
        public static string Membership_Fax {
            get {
                return ResourceManager.GetString("Membership_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        public static string Membership_Firstname {
            get {
                return ResourceManager.GetString("Membership_Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ (ภาษาอังกฤษ).
        /// </summary>
        public static string Membership_FirstnameEN {
            get {
                return ResourceManager.GetString("Membership_FirstnameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        public static string Membership_FirstnameTH {
            get {
                return ResourceManager.GetString("Membership_FirstnameTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขสมาชิก.
        /// </summary>
        public static string Membership_Id {
            get {
                return ResourceManager.GetString("Membership_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตำแหน่ง.
        /// </summary>
        public static string Membership_JobTitle {
            get {
                return ResourceManager.GetString("Membership_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นามสกุล.
        /// </summary>
        public static string Membership_Lastname {
            get {
                return ResourceManager.GetString("Membership_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นามสกุล (ภาษาอังกฤษ).
        /// </summary>
        public static string Membership_LastnameEN {
            get {
                return ResourceManager.GetString("Membership_LastnameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นามสกุล.
        /// </summary>
        public static string Membership_LastnameTH {
            get {
                return ResourceManager.GetString("Membership_LastnameTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสสมาชิกสถาบัน (ถ้ามี).
        /// </summary>
        public static string Membership_MembershipNumber {
            get {
                return ResourceManager.GetString("Membership_MembershipNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทสมาชิก.
        /// </summary>
        public static string Membership_MembershipRegisterType {
            get {
                return ResourceManager.GetString("Membership_MembershipRegisterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โทรศัพท์มือถือ.
        /// </summary>
        public static string Membership_Mobile {
            get {
                return ResourceManager.GetString("Membership_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผ่าน.
        /// </summary>
        public static string Membership_Password {
            get {
                return ResourceManager.GetString("Membership_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันรหัสผ่าน.
        /// </summary>
        public static string Membership_Password_Re {
            get {
                return ResourceManager.GetString("Membership_Password_Re", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสไปรษณีย์.
        /// </summary>
        public static string Membership_Postcode {
            get {
                return ResourceManager.GetString("Membership_Postcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จังหวัด.
        /// </summary>
        public static string Membership_Province {
            get {
                return ResourceManager.GetString("Membership_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำถาม.
        /// </summary>
        public static string Membership_Question {
            get {
                return ResourceManager.GetString("Membership_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่สมัคร.
        /// </summary>
        public static string Membership_RegisterDate {
            get {
                return ResourceManager.GetString("Membership_RegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันหมดอายุ.
        /// </summary>
        public static string Membership_RegisterDateExp {
            get {
                return ResourceManager.GetString("Membership_RegisterDateExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ศาสนา.
        /// </summary>
        public static string Membership_Religion {
            get {
                return ResourceManager.GetString("Membership_Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ถนน.
        /// </summary>
        public static string Membership_Road {
            get {
                return ResourceManager.GetString("Membership_Road", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รัฐ.
        /// </summary>
        public static string Membership_State {
            get {
                return ResourceManager.GetString("Membership_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โทรศัพท์.
        /// </summary>
        public static string Membership_Tel {
            get {
                return ResourceManager.GetString("Membership_Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันสมาชิกเสร็จสมบูรณ์.
        /// </summary>
        public static string MembershipConfirm {
            get {
                return ResourceManager.GetString("MembershipConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สมาชิกสถาบัน.
        /// </summary>
        public static string MembershipCRM {
            get {
                return ResourceManager.GetString("MembershipCRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เมนู.
        /// </summary>
        public static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายการปลีกย่อย.
        /// </summary>
        public static string Miscellaneous_items {
            get {
                return ResourceManager.GetString("Miscellaneous_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โอนเงิน.
        /// </summary>
        public static string Money_transfer {
            get {
                return ResourceManager.GetString("Money_transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อผู้ส่ง.
        /// </summary>
        public static string Name_send {
            get {
                return ResourceManager.GetString("Name_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มีข้อมูล.
        /// </summary>
        public static string No_data {
            get {
                return ResourceManager.GetString("No_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มี.
        /// </summary>
        public static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคาต่อหน่วย.
        /// </summary>
        public static string Normal_Price {
            get {
                return ResourceManager.GetString("Normal_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่กำหนด.
        /// </summary>
        public static string not_defined {
            get {
                return ResourceManager.GetString("not_defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไฟล์ประกอบ.
        /// </summary>
        public static string Notes_file {
            get {
                return ResourceManager.GetString("Notes_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อาชีพ.
        /// </summary>
        public static string Occupation {
            get {
                return ResourceManager.GetString("Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โทรสารที่ทำงาน.
        /// </summary>
        public static string Office_Fax {
            get {
                return ResourceManager.GetString("Office_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โทรศัพท์ที่ทำงาน.
        /// </summary>
        public static string Office_Phone {
            get {
                return ResourceManager.GetString("Office_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บริการออนไลน์.
        /// </summary>
        public static string OnlineService {
            get {
                return ResourceManager.GetString("OnlineService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายการสั่งซื้อสินค้า.
        /// </summary>
        public static string Order_list {
            get {
                return ResourceManager.GetString("Order_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขที่การสั่งซื้อ.
        /// </summary>
        public static string Order_number {
            get {
                return ResourceManager.GetString("Order_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายการสั่งซื้อของคุณชำระเรียบร้อย.
        /// </summary>
        public static string Order_your_payment_successful {
            get {
                return ResourceManager.GetString("Order_your_payment_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อผู้สั่งซื้อ / ผู้จัดส่งสินค้า.
        /// </summary>
        public static string ordering_name__delivery_authority {
            get {
                return ResourceManager.GetString("ordering_name__delivery_authority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สินค้าหมด.
        /// </summary>
        public static string Out_of_stock {
            get {
                return ResourceManager.GetString("Out_of_stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การตั้งค่ารหัสผ่านใหม่.
        /// </summary>
        public static string Password_Resetting {
            get {
                return ResourceManager.GetString("Password_Resetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผ่านต้องมีความยาวมากกว่า 8 ตัวอักษร.
        /// </summary>
        public static string PasswordMustBeLongerThan8Characters {
            get {
                return ResourceManager.GetString("PasswordMustBeLongerThan8Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคา.
        /// </summary>
        public static string Pay_Price {
            get {
                return ResourceManager.GetString("Pay_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวน.
        /// </summary>
        public static string Pay_Quantity {
            get {
                return ResourceManager.GetString("Pay_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การชำระเงินเสร็จสมบูรณ์.
        /// </summary>
        public static string Payment_Completed {
            get {
                return ResourceManager.GetString("Payment_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หลักฐานการจ่ายเงิน.
        /// </summary>
        public static string Payment_Proof {
            get {
                return ResourceManager.GetString("Payment_Proof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทการชำระ.
        /// </summary>
        public static string Payment_type {
            get {
                return ResourceManager.GetString("Payment_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เบอร์โทรศัพท์.
        /// </summary>
        public static string Phonenumber {
            get {
                return ResourceManager.GetString("Phonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณายอมรับข้อกำหนดเเละเงื่อนไขเพื่อดำเนินการชำระเงินต่อไป.
        /// </summary>
        public static string Please_accept_the_terms_and_conditions_to_continue_payment {
            get {
                return ResourceManager.GetString("Please_accept_the_terms_and_conditions_to_continue_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาทำเครื่องหมายด้านหน้าเพื่อยืนยันว่าคุณได้ศึกษาเเละยอมรับใน.
        /// </summary>
        public static string Please_check_this_box_for_confirm_that_you_have_already_read_and_accepted_into {
            get {
                return ResourceManager.GetString("Please_check_this_box_for_confirm_that_you_have_already_read_and_accepted_into", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสไปรษณีย์.
        /// </summary>
        public static string Postcode {
            get {
                return ResourceManager.GetString("Postcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคา.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคาต่อหน่วย.
        /// </summary>
        public static string Price_Per_Unit {
            get {
                return ResourceManager.GetString("Price_Per_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สินค้า.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วัน.
        /// </summary>
        public static string Product_Date {
            get {
                return ResourceManager.GetString("Product_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสสินค้า.
        /// </summary>
        public static string Product_id {
            get {
                return ResourceManager.GetString("Product_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ภาษา.
        /// </summary>
        public static string Product_Language {
            get {
                return ResourceManager.GetString("Product_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อสินค้า.
        /// </summary>
        public static string Product_name {
            get {
                return ResourceManager.GetString("Product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคาต่อหน่วย.
        /// </summary>
        public static string Product_Price {
            get {
                return ResourceManager.GetString("Product_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลา.
        /// </summary>
        public static string Product_Time {
            get {
                return ResourceManager.GetString("Product_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หลักสูตร.
        /// </summary>
        public static string Product_Title {
            get {
                return ResourceManager.GetString("Product_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จังหวัด.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวน.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายละเอียดการจัดส่ง ใบเสร็จรับเงิน.
        /// </summary>
        public static string ReceiptInfo {
            get {
                return ResourceManager.GetString("ReceiptInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ออกในนาม.
        /// </summary>
        public static string Receipts_issued_in_the_name {
            get {
                return ResourceManager.GetString("Receipts_issued_in_the_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นำออกจากตะกร้า.
        /// </summary>
        public static string Remove_in_cart {
            get {
                return ResourceManager.GetString("Remove_in_cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกคำตอบ.
        /// </summary>
        public static string RequiredAnswer {
            get {
                return ResourceManager.GetString("RequiredAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกข้อมูล.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกไฟล์.
        /// </summary>
        public static string RequiredFile {
            get {
                return ResourceManager.GetString("RequiredFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกชื่อ.
        /// </summary>
        public static string RequiredFirstname {
            get {
                return ResourceManager.GetString("RequiredFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกนามสกุล.
        /// </summary>
        public static string RequiredLastname {
            get {
                return ResourceManager.GetString("RequiredLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกคำถาม.
        /// </summary>
        public static string RequiredQuestion {
            get {
                return ResourceManager.GetString("RequiredQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกจำนวนเงิน.
        /// </summary>
        public static string RequiredTotalPrice {
            get {
                return ResourceManager.GetString("RequiredTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่งอีกครั้ง.
        /// </summary>
        public static string Resend {
            get {
                return ResourceManager.GetString("Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกซื้อสินค้าเพิ่ม.
        /// </summary>
        public static string Select_more {
            get {
                return ResourceManager.GetString("Select_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสพัสดุคือ.
        /// </summary>
        public static string Shipment_number {
            get {
                return ResourceManager.GetString("Shipment_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ได้จัดส่งสินค้าของท่านแล้ว.
        /// </summary>
        public static string Shipment_send_success {
            get {
                return ResourceManager.GetString("Shipment_send_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขที่การจัดส่ง.
        /// </summary>
        public static string ShipmentNumber {
            get {
                return ResourceManager.GetString("ShipmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตะกร้าสินค้า.
        /// </summary>
        public static string Shopping_cart {
            get {
                return ResourceManager.GetString("Shopping_cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สินค้าในตะกร้า.
        /// </summary>
        public static string Shopping_in_cart {
            get {
                return ResourceManager.GetString("Shopping_in_cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระยะสั้น.
        /// </summary>
        public static string shortTerm {
            get {
                return ResourceManager.GetString("shortTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขนาดไม่เกิน 10 MB.
        /// </summary>
        public static string SizeMustNotMoreThan10MB {
            get {
                return ResourceManager.GetString("SizeMustNotMoreThan10MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะ.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บาท.
        /// </summary>
        public static string THB {
            get {
                return ResourceManager.GetString("THB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สินค้าได้จัดส่งแล้ว.
        /// </summary>
        public static string The_shipment_of_you {
            get {
                return ResourceManager.GetString("The_shipment_of_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อกำหนดเเละเงื่อนไขในการรับเงิน.
        /// </summary>
        public static string The_term_and_conditions_to_receiving_the_money {
            get {
                return ResourceManager.GetString("The_term_and_conditions_to_receiving_the_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ท่านไม่ดำเนินการตั้งรหัสผ่านในเวลาที่กาหนด กรุณากรอกข้อมูลของท่านเพื่อตั้งรหัสผ่านใหม่.
        /// </summary>
        public static string Timeout_resetpasswordMessage {
            get {
                return ResourceManager.GetString("Timeout_resetpasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดรวม.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคาสุทธิ.
        /// </summary>
        public static string Total_price {
            get {
                return ResourceManager.GetString("Total_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การดำเนินการถูกปฎิเสธ.
        /// </summary>
        public static string transaction_declined {
            get {
                return ResourceManager.GetString("transaction_declined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทการฝึกอบรม.
        /// </summary>
        public static string type_of_training {
            get {
                return ResourceManager.GetString("type_of_training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชิ้น.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไฟล์รูปภาพขนาดไม่เกิน 10 MB.
        /// </summary>
        public static string UpTo10MbPerImage {
            get {
                return ResourceManager.GetString("UpTo10MbPerImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD.
        /// </summary>
        public static string USD {
            get {
                return ResourceManager.GetString("USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกอีเมล.
        /// </summary>
        public static string Validation_Email {
            get {
                return ResourceManager.GetString("Validation_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมลไม่ตรงกัน.
        /// </summary>
        public static string Validation_EmailConfirm {
            get {
                return ResourceManager.GetString("Validation_EmailConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมลไม่ถูกต้อง.
        /// </summary>
        public static string Validation_EmailCorrect {
            get {
                return ResourceManager.GetString("Validation_EmailCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เบอร์โทรสารไม่ถูกต้อง.
        /// </summary>
        public static string Validation_FaxNoCorrect {
            get {
                return ResourceManager.GetString("Validation_FaxNoCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกชื่อ.
        /// </summary>
        public static string Validation_Firstname {
            get {
                return ResourceManager.GetString("Validation_Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลไม่ถูกต้อง.
        /// </summary>
        public static string Validation_InformationIncorrect {
            get {
                return ResourceManager.GetString("Validation_InformationIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกนามสกุล.
        /// </summary>
        public static string Validation_Lastname {
            get {
                return ResourceManager.GetString("Validation_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เบอร์โทรศัพท์มือถือไม่ถูกต้อง.
        /// </summary>
        public static string Validation_MobileNoCorrect {
            get {
                return ResourceManager.GetString("Validation_MobileNoCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกรหัสผ่าน.
        /// </summary>
        public static string Validation_Password {
            get {
                return ResourceManager.GetString("Validation_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผ่านไม่ตรงกัน.
        /// </summary>
        public static string Validation_PasswordConfirm {
            get {
                return ResourceManager.GetString("Validation_PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เบอร์โทรศัพท์ไม่ถูกต้อง.
        /// </summary>
        public static string Validation_TelNoCorrect {
            get {
                return ResourceManager.GetString("Validation_TelNoCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสไปรษณีย์ไม่ถูกต้อง.
        /// </summary>
        public static string Validation_ZipcodeCorrect {
            get {
                return ResourceManager.GetString("Validation_ZipcodeCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ภาษีมูลค่าเพิ่ม.
        /// </summary>
        public static string Vat {
            get {
                return ResourceManager.GetString("Vat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดูทั้งหมด.
        /// </summary>
        public static string View_More {
            get {
                return ResourceManager.GetString("View_More", resourceCulture);
            }
        }
    }
}
