//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amphur
    {
        public Amphur()
        {
            this.Districts = new HashSet<District>();
        }
    
        public int AMPHUR_ID { get; set; }
        public string AMPHUR_CODE { get; set; }
        public string AMPHUR_NAME { get; set; }
        public string POSTCODE { get; set; }
        public int GEO_ID { get; set; }
        public int PROVINCE_ID { get; set; }
    
        public virtual Province Province { get; set; }
        public virtual ICollection<District> Districts { get; set; }
    }
}
