//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git_system.Models
{
    using Git_system.Notifications;
    using System;
    using System.Collections.Generic;
    
    public partial class BaseDevice
    {
        public int Id { get; set; }
        public string DeviceIdentifier { get; set; }
        public string Type { get; set; }
        public int MembershipId { get; set; }
    
        public virtual Membership Membership { get; set; }

        public Device toDevice()
        {
            return new Device(this.DeviceIdentifier,this.Type);
        }
    }
}
