//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git_system.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ConfirmPaymentBankType
    {
        public ConfirmPaymentBankType()
        {
            this.ConfirmPayments = new HashSet<ConfirmPayment>();
            this.EComConfirmOrders = new HashSet<EComConfirmOrder>();
        }
    
        public short Id { get; set; }
        [Required(ErrorMessageResourceType = typeof(MultiResources.Multi), ErrorMessageResourceName = "RequiredField")]
        public string NameTH { get; set; }
        [Required(ErrorMessageResourceType = typeof(MultiResources.Multi), ErrorMessageResourceName = "RequiredField")]
        public string NameEN { get; set; }
        public string DetailTH { get; set; }
        public string DetailEN { get; set; }
        [Required(ErrorMessageResourceType = typeof(MultiResources.Multi), ErrorMessageResourceName = "RequiredField")]
        public string BanknameTH { get; set; }
        [Required(ErrorMessageResourceType = typeof(MultiResources.Multi), ErrorMessageResourceName = "RequiredField")]
        public string BanknameEN { get; set; }
        [Required(ErrorMessageResourceType = typeof(MultiResources.Multi), ErrorMessageResourceName = "RequiredField")]
        public string BranchTH { get; set; }
        [Required(ErrorMessageResourceType = typeof(MultiResources.Multi), ErrorMessageResourceName = "RequiredField")]
        public string BranchEN { get; set; }
        [Required(ErrorMessageResourceType = typeof(MultiResources.Multi), ErrorMessageResourceName = "RequiredField")]
        public string AccountNo { get; set; }
    
        public virtual ICollection<ConfirmPayment> ConfirmPayments { get; set; }
        public virtual ICollection<EComConfirmOrder> EComConfirmOrders { get; set; }
    }
}
