//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git_system.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ConfirmPayment
    {
        public int Id { get; set; }
        public string Invoice { get; set; }
        public string Name { get; set; }
        [Required(ErrorMessageResourceType = typeof(MultiResources.Multi), ErrorMessageResourceName = "RequiredTotalPrice")]
        public double Total { get; set; }
        public string Tel { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Filename { get; set; }
        public string Other { get; set; }
        public Nullable<short> ConfirmPaymentBankTypeId { get; set; }
        public int PayId { get; set; }
        public string FilenameConfirm { get; set; }
        public string Currency { get; set; }
        public string CreditCardRefNo { get; set; }
    
        public virtual ConfirmPaymentBankType ConfirmPaymentBankType { get; set; }
        public virtual Pay Pay { get; set; }
    }
}
