//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git_system.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database_MainEntities1 : DbContext
    {
        public Database_MainEntities1()
            : base("name=Database_MainEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Log> Logs { get; set; }
        public DbSet<UserAdmin> UserAdmins { get; set; }
        public DbSet<Permission> Permissions { get; set; }
        public DbSet<ProcessStatusType> ProcessStatusTypes { get; set; }
        public DbSet<PayType> PayTypes { get; set; }
        public DbSet<PayItem> PayItems { get; set; }
        public DbSet<Pay> Pays { get; set; }
        public DbSet<Membership> Memberships { get; set; }
        public DbSet<MembershipRegisterType> MembershipRegisterTypes { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Course> Courses { get; set; }
        public DbSet<ConfirmPayment> ConfirmPayments { get; set; }
        public DbSet<ConfirmPaymentBankType> ConfirmPaymentBankTypes { get; set; }
        public DbSet<EmailMessage> EmailMessages { get; set; }
        public DbSet<ProductSKU> ProductSKUs { get; set; }
        public DbSet<Province> Provinces { get; set; }
        public DbSet<Amphur> Amphurs { get; set; }
        public DbSet<District> Districts { get; set; }
        public DbSet<Geography> Geographies { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<QuestionList> QuestionLists { get; set; }
        public DbSet<ProductNews> ProductNews { get; set; }
        public DbSet<Benefit> Benefits { get; set; }
        public DbSet<Translate> Translates { get; set; }
        public DbSet<VatType> VatTypes { get; set; }
        public DbSet<TranslateMap> TranslateMaps { get; set; }
        public DbSet<EComProduct> EComProducts { get; set; }
        public DbSet<EComCategory> EComCategories { get; set; }
        public DbSet<EComCategoryMap> EComCategoryMaps { get; set; }
        public DbSet<EComOrder> EComOrders { get; set; }
        public DbSet<EComOrderItem> EComOrderItems { get; set; }
        public DbSet<EComConfirmOrder> EComConfirmOrders { get; set; }
        public DbSet<EComPromotion> EComPromotions { get; set; }
        public DbSet<EComLogView> EComLogViews { get; set; }
        public DbSet<EComKeyword> EComKeywords { get; set; }
        public DbSet<PaymentProcessStatus> PaymentProcessStatus { get; set; }
        public DbSet<DeliverProcessStatus> DeliverProcessStatus { get; set; }
        public DbSet<EComDeliverType> EComDeliverTypes { get; set; }
        public DbSet<DeliverType> DeliverTypes { get; set; }
        public DbSet<EComProductDeliver> EComProductDelivers { get; set; }
        public DbSet<Slideshow> Slideshows { get; set; }
        public DbSet<SlideshowTranslate> SlideshowTranslates { get; set; }
        public DbSet<EComDeliverPromotion> EComDeliverPromotions { get; set; }
        public DbSet<EComDeliverPromotionMap> EComDeliverPromotionMaps { get; set; }
        public DbSet<BaseDevice> BaseDevices { get; set; }
    }
}
