//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliverType
    {
        public DeliverType()
        {
            this.EComProductDelivers = new HashSet<EComProductDeliver>();
        }
    
        public int Id { get; set; }
        public int NameTranslateId { get; set; }
    
        public virtual TranslateMap NameTranslateMap { get; set; }
        public virtual ICollection<EComProductDeliver> EComProductDelivers { get; set; }
    }
}
