//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git_system.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class EComDeliverType
    {
        public EComDeliverType()
        {
            this.PriceTH = 0D;
            this.PriceUS = 0D;
            this.EComOrders = new HashSet<EComOrder>();
        }

        public int Id { get; set; }

        [Required(ErrorMessageResourceType = typeof(MultiResources.Multi), ErrorMessageResourceName = "RequiredField")]
        public string NameTH { get; set; }

        [Required(ErrorMessageResourceType = typeof(MultiResources.Multi), ErrorMessageResourceName = "RequiredField")]
        public string NameEN { get; set; }

        public string DetailTH { get; set; }
        public string DetailEN { get; set; }
        public double PriceTH { get; set; }
        public double PriceUS { get; set; }
    
        public virtual ICollection<EComOrder> EComOrders { get; set; }
    }
}
