//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git_system.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class EComDeliverPromotion
    {
        public EComDeliverPromotion()
        {
            this.Percent = 0D;
            this.Type = 1;
            this.ActiveStatus = false;
            this.isGuest = false;
            this.isGuestInter = false;
            this.isIndividual = false;
            this.isIndividualInter = false;
            this.isCorporate = false;
            this.isCorparateInter = false;
            this.EComDeliverPromotionMaps = new HashSet<EComDeliverPromotionMap>();
        }
    
        public int Id { get; set; }

        [Required(ErrorMessageResourceType = typeof(MultiResources.Multi), ErrorMessageResourceName = "RequiredField")]
        public string NameTh { get; set; }

        [Required(ErrorMessageResourceType = typeof(MultiResources.Multi), ErrorMessageResourceName = "RequiredField")]
        public string NameEn { get; set; }

        [Range(1, 100, ErrorMessage = "ต้องอยู่ระหว่าง 1 - 100")]
        [Required(ErrorMessageResourceType = typeof(MultiResources.Multi), ErrorMessageResourceName = "RequiredField")]
        public double Percent { get; set; }

        [Required(ErrorMessageResourceType = typeof(MultiResources.Multi), ErrorMessageResourceName = "RequiredField")]
        public int Type { get; set; }

        public Nullable<int> Operator { get; set; }
        public Nullable<int> Operator2 { get; set; }
        public bool ActiveStatus { get; set; }
        public bool isGuest { get; set; }
        public bool isGuestInter { get; set; }
        public bool isIndividual { get; set; }
        public bool isIndividualInter { get; set; }
        public bool isCorporate { get; set; }
        public bool isCorparateInter { get; set; }
    
        public virtual ICollection<EComDeliverPromotionMap> EComDeliverPromotionMaps { get; set; }
    }
}
