//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git_system.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class EComCategory
    {
        public EComCategory()
        {
            this.ActiveStatus = false;
            this.VisibleStatus = false;
            this.ShowOnPageStatus = false;
            this.SortOrderStatus = false;
            this.Price = 0D;
            this.PriceInter = 0D;
            this.EComCategoryMaps = new HashSet<EComCategoryMap>();
            this.EComPromotions = new HashSet<EComPromotion>();
        }
    
        public int Id { get; set; }

        [Required(ErrorMessageResourceType = typeof(MultiResources.Multi), ErrorMessageResourceName = "RequiredField")]
        public string NameTH { get; set; }

        [Required(ErrorMessageResourceType = typeof(MultiResources.Multi), ErrorMessageResourceName = "RequiredField")]
        public string NameEN { get; set; }

        public string DetailTH { get; set; }
        public string DetailEN { get; set; }
        public bool ActiveStatus { get; set; }
        public bool VisibleStatus { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public bool ShowOnPageStatus { get; set; }
        public bool SortOrderStatus { get; set; }
        public double Price { get; set; }
        public double PriceInter { get; set; }
    
        public virtual ICollection<EComCategoryMap> EComCategoryMaps { get; set; }
        public virtual ICollection<EComPromotion> EComPromotions { get; set; }
    }
}
