//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git_system.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class EComPromotion
    {
        public EComPromotion()
        {
            this.isGuest = false;
            this.isGuestInter = false;
            this.isIndividual = false;
            this.isIndividualInter = false;
            this.isCorporate = false;
            this.isCorporateInter = false;
            this.Percent = 0D;
            this.Operator = 0;
            this.ActiveStatus = false;
        }

        public int Id { get; set; }

        [Required(ErrorMessageResourceType = typeof(MultiResources.Multi), ErrorMessageResourceName = "RequiredField")]
        public string NameTH { get; set; }

        [Required(ErrorMessageResourceType = typeof(MultiResources.Multi), ErrorMessageResourceName = "RequiredField")]
        public string NameEN { get; set; }
        public string DetailTH { get; set; }
        public string DetailEN { get; set; }
        public bool isGuest { get; set; }
        public bool isGuestInter { get; set; }
        public bool isIndividual { get; set; }
        public bool isIndividualInter { get; set; }
        public bool isCorporate { get; set; }
        public bool isCorporateInter { get; set; }

        [Range(1, 100, ErrorMessage = "ต้องอยู่ระหว่าง 1 - 100")]
        [Required(ErrorMessageResourceType = typeof(MultiResources.Multi), ErrorMessageResourceName = "RequiredField")]
        public double Percent { get; set; }
        public int Operator { get; set; }
        public int Type { get; set; }
        public bool ActiveStatus { get; set; }
        public Nullable<int> EComCategoryId { get; set; }
        public Nullable<int> EComProductId { get; set; }
    
        public virtual EComCategory EComCategory { get; set; }
        public virtual EComProduct EComProduct { get; set; }
    }
}
