//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EComConfirmOrder
    {
        public int Id { get; set; }
        public int EComOrderId { get; set; }
        public double Price { get; set; }
        public System.DateTime Datetime { get; set; }
        public string FilenamePayment { get; set; }
        public string FilenameConfirm { get; set; }
        public Nullable<short> ConfirmPaymentBankTypeId { get; set; }
        public string CreditCardRefNo { get; set; }
        public string Currency { get; set; }
    
        public virtual EComOrder EComOrder { get; set; }
        public virtual ConfirmPaymentBankType ConfirmPaymentBankType { get; set; }
    }
}
