//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git_system.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class EComOrder
    {
        public EComOrder()
        {
            this.PaymentProcessStatusId = 1;
            this.DeliverProcessStatusId = 1;
            this.DeliverNumber = "";
            this.EComOrderItems = new HashSet<EComOrderItem>();
            this.EComConfirmOrders = new HashSet<EComConfirmOrder>();
        }
    
        public int Id { get; set; }
        public System.DateTime Datetime { get; set; }
        public int MembershipId { get; set; }
        public double Price { get; set; }
        public string Currency { get; set; }
        public int PaymentType { get; set; }
        public int PaymentProcessStatusId { get; set; }
        public int DeliverProcessStatusId { get; set; }
        public string DeliverNumber { get; set; }
        public string SendFullname { get; set; }
        public string SendAddress { get; set; }
        public string SendProvince { get; set; }
        public string SendCountry { get; set; }
        public string SendPostcode { get; set; }
        public string SendPhonenumber { get; set; }
        public string SendEmail { get; set; }
        public string ReceiptFullname { get; set; }
        public string ReceiptAddress { get; set; }
        public string ReceiptProvince { get; set; }
        public string ReceiptCountry { get; set; }
        public string ReceiptPostcode { get; set; }
        public string ReceiptPhonenumber { get; set; }
        public string ReceiptEmail { get; set; }
        public int EComDeliverTypeId { get; set; }
        public string DeliverSendName { get; set; }

        [DataType(DataType.Date, ErrorMessage = "วัน-เวลาไม่ถูกต้อง")]
        [Range(typeof(DateTime), "2500-1-1", "3000-12-31", ErrorMessage = "วัน-เวลาไม่ถูกต้อง ปีต้องเป็น พ.ศ เท่านั้น")]
        public Nullable<System.DateTime> DeliverSendDate { get; set; }
        public string JOrderDetail { get; set; }
    
        public virtual Membership Membership { get; set; }
        public virtual ICollection<EComOrderItem> EComOrderItems { get; set; }
        public virtual ICollection<EComConfirmOrder> EComConfirmOrders { get; set; }
        public virtual PaymentProcessStatus PaymentProcessStatu { get; set; }
        public virtual DeliverProcessStatus DeliverProcessStatu { get; set; }
        public virtual EComDeliverType EComDeliverType { get; set; }
    }
}
