//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailMessage
    {
        public short Id { get; set; }
        public string TitleTH { get; set; }
        public string TitleEN { get; set; }
        public string MessageTH { get; set; }
        public string MessageEN { get; set; }
        public string EmailAlert { get; set; }
    }
}
