//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Massage { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<int> UserAdminId { get; set; }
    
        public virtual UserAdmin UserAdmin { get; set; }
    }
}
