//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membership
    {
        private void setDefault(){
            this.Active = false;
            this.ExperienceInGem = false;
            this.Pays = new HashSet<Pay>();
            this.EComOrders = new HashSet<EComOrder>();
            this.EComLogViews = new HashSet<EComLogView>();
            this.EComKeywords = new HashSet<EComKeyword>();
            this.Devices = new HashSet<BaseDevice>();
        }

        public Membership()
        {
            setDefault();
        }

        public Membership(short membershipType)
        {
            setDefault();
            this.MembershipRegisterTypeId = membershipType;
        }

        public Membership(int membershipId, short membershipType)
        {
            setDefault();
            this.Id = membershipId;
            this.MembershipRegisterTypeId = membershipType;
        }
    
        public int Id { get; set; }
        public string TitleName { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string FirstnameTH { get; set; }
        public string LastnameTH { get; set; }
        public string FirstnameEN { get; set; }
        public string LastnameEN { get; set; }
        public string Company { get; set; }
        public string WorkTel { get; set; }
        public string WorkFax { get; set; }
        public string JobTitle { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<System.DateTime> RegisterDateExp { get; set; }
        public short MembershipRegisterTypeId { get; set; }
        public string IdCRM { get; set; }
        public string GroupCRM { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string Religion { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public bool Active { get; set; }
        public int QuestionListId { get; set; }
        public string MobileCRM { get; set; }
        public Nullable<System.DateTime> ExpCRM { get; set; }
        public string IdentificationNo { get; set; }
        public string Occupation { get; set; }
        public string Education { get; set; }
        public bool ExperienceInGem { get; set; }
    
        public virtual ICollection<Pay> Pays { get; set; }
        public virtual MembershipRegisterType MembershipRegisterType { get; set; }
        public virtual QuestionList QuestionList { get; set; }
        public virtual ICollection<EComOrder> EComOrders { get; set; }
        public virtual ICollection<EComLogView> EComLogViews { get; set; }
        public virtual ICollection<EComKeyword> EComKeywords { get; set; }
        public virtual ICollection<BaseDevice> Devices { get; set; }
    }
}
