//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay
    {
        public Pay()
        {
            this.Type = 2;
            this.Price = 0D;
            this.PayItems = new HashSet<PayItem>();
            this.ConfirmPayments = new HashSet<ConfirmPayment>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int MembershipId { get; set; }
        public short PayTypeId { get; set; }
        public short ProcessStatusTypeId { get; set; }
        public short Type { get; set; }
        public double Price { get; set; }
        public string Fullname { get; set; }
        public string Address { get; set; }
        public string Currency { get; set; }
        public string Note { get; set; }
    
        public virtual Membership Membership { get; set; }
        public virtual ICollection<PayItem> PayItems { get; set; }
        public virtual PayType PayType { get; set; }
        public virtual ProcessStatusType ProcessStatusType { get; set; }
        public virtual ICollection<ConfirmPayment> ConfirmPayments { get; set; }
    }
}
