//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git_system.Models
{
    using System;
    using System.Collections.Generic;

    public partial class PayItem : ICloneable
    {
        public int Id { get; set; }
        public short Quantity { get; set; }
        public int PayId { get; set; }
        public int CourseId { get; set; }
    
        public virtual Pay Pay { get; set; }
        public virtual Course Course { get; set; }

        public object Clone()
        {
            return this.MemberwiseClone();
        }
    }
}
