//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentProcessStatus
    {
        public PaymentProcessStatus()
        {
            this.EComOrders = new HashSet<EComOrder>();
        }
    
        public int Id { get; set; }
        public string NameTH { get; set; }
        public string NameEN { get; set; }
    
        public virtual ICollection<EComOrder> EComOrders { get; set; }
    }
}
