//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessStatusType
    {
        public ProcessStatusType()
        {
            this.Pays = new HashSet<Pay>();
        }
    
        public short Id { get; set; }
        public string Name { get; set; }
        public string Detail { get; set; }
    
        public virtual ICollection<Pay> Pays { get; set; }
    }
}
