//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git_system.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ProductSKU
    {
        public ProductSKU()
        {
            this.Percent = 0D;
            this.isGuest = false;
            this.isGuest_Inter = false;
            this.isIndividual = false;
            this.isIndividual_Inter = false;
            this.isCorporate = false;
            this.isCorporate_Inter = false;
            this.Active = true;
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "ต้องไม่เป็นค่าว่าง")]
        public string NameTH { get; set; }
        [Required(ErrorMessage = "ต้องไม่เป็นค่าว่าง")]
        public string NameEN { get; set; }

        [Range(1, 100, ErrorMessage = "ต้องอยู่ระหว่าง 1 - 100")]
        [Required(ErrorMessageResourceType = typeof(MultiResources.Multi), ErrorMessageResourceName = "RequiredField")]
        public double Percent { get; set; }
        public bool isGuest { get; set; }
        public bool isGuest_Inter { get; set; }
        public bool isIndividual { get; set; }
        public bool isIndividual_Inter { get; set; }
        public bool isCorporate { get; set; }
        public bool isCorporate_Inter { get; set; }
        public bool Active { get; set; }
        public Nullable<int> Operator { get; set; }
        public int Type { get; set; }
        public Nullable<int> CourseId { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
