//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionList
    {
        public QuestionList()
        {
            this.Memberships = new HashSet<Membership>();
        }
    
        public int Id { get; set; }
        public string QuestionTH { get; set; }
        public string QuestionEN { get; set; }
    
        public virtual ICollection<Membership> Memberships { get; set; }
    }
}
