//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git_system.Models
{
    using System.Collections.Generic;
    using System.Linq;

    public partial class Slideshow
    {
        public Slideshow()
        {
            this.Status = false;
            this.OrderBy = 0;
            this.SlideshowTranslates = new HashSet<SlideshowTranslate>();
        }

        public int Id { get; set; }
        public string Image { get; set; }
        public bool Status { get; set; }
        public int OrderBy { get; set; }

        public string getImageUrl()
        {
            var imageFiles = new List<ECom.FileLink>();
            if (this.Image != null) { imageFiles = Newtonsoft.Json.JsonConvert.DeserializeObject<List<ECom.FileLink>>(this.Image); }
            if(imageFiles.Count != 0)
                return imageFiles.FirstOrDefault().FilePath.Replace("~", "");
            return "";
        }
        public SlideshowTranslate getSlideshowTranslate(string language_code)
        {
            return this.SlideshowTranslates.Where(s => s.Language_code.Equals(language_code.ToLower())).FirstOrDefault() ?? new SlideshowTranslate(language_code.ToLower());
        }

        public string Link { get; set; }
    
        public virtual ICollection<SlideshowTranslate> SlideshowTranslates { get; set; }
    }
}
