//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlideshowTranslate
    {
        public int Id { get; set; }
        public string Language_code { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int SlideshowId { get; set; }

        public SlideshowTranslate() { }
        public SlideshowTranslate(string language_code) {
            this.Language_code = language_code;
        }

    
        public virtual Slideshow Slideshow { get; set; }
    }
}
