//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translate
    {
        public int Id { get; set; }
        public int TranslateMapId { get; set; }
        public string Language_code { get; set; }
        public string Text { get; set; }
    
        public virtual TranslateMap TranslateMap { get; set; }
    }
}
