//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranslateMap
    {
        public TranslateMap()
        {
            this.Translates = new HashSet<Translate>();
            this.VatTypes = new HashSet<VatType>();
            this.DeliverTypes = new HashSet<DeliverType>();
        }
    
        public int Id { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<Translate> Translates { get; set; }
        public virtual ICollection<VatType> VatTypes { get; set; }
        public virtual ICollection<DeliverType> DeliverTypes { get; set; }
    }
}
