//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git_system.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class UserAdmin
    {
        public UserAdmin()
        {
            this.Active = true;
            this.Logs = new HashSet<Log>();
        }
    
        public int Id { get; set; }

        [Required(ErrorMessageResourceType = typeof(MultiResources.Multi), ErrorMessageResourceName = "RequiredField")]
        [Display(Name = "User name")]
        public string userName { get; set; }

        [Display(Name = "Password")]
        public string Password { get; set; }

        [Required(ErrorMessageResourceType = typeof(MultiResources.Multi), ErrorMessageResourceName = "RequiredField")]
        [Display(Name = "First name")]
        public string Firstname { get; set; }

        [Required(ErrorMessageResourceType = typeof(MultiResources.Multi), ErrorMessageResourceName = "RequiredField")]
        [Display(Name = "Last name")]
        public string Lastname { get; set; }

        [Display(Name = "Job title")]
        public string JobTitle { get; set; }

        public string Department { get; set; }

        [Required(ErrorMessageResourceType = typeof(MultiResources.Multi), ErrorMessageResourceName = "RequiredField")]
        [Display(Name = "Email")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$",
                ErrorMessageResourceType = typeof(MultiResources.Multi), ErrorMessageResourceName = "Validation_EmailCorrect")]
        public string Email { get; set; }

        [Display(Name = "Tel")]
        public string Tel { get; set; }

        public bool Active { get; set; }

        [Required(ErrorMessageResourceType = typeof(MultiResources.Multi), ErrorMessageResourceName = "RequiredField")]
        public int Permission_permissionId { get; set; }

        public Nullable<System.DateTime> LastSignIn { get; set; }
    
        public virtual Permission Permission { get; set; }
        public virtual ICollection<Log> Logs { get; set; }
    }
}
