//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Git_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VatType
    {
        public VatType()
        {
            this.Products = new HashSet<Product>();
            this.EComProducts = new HashSet<EComProduct>();
        }
    
        public int Id { get; set; }
        public int NameTranslate { get; set; }
    
        public virtual TranslateMap TranslateMap { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<EComProduct> EComProducts { get; set; }
    }
}
